# Problem 1 

In [ ]:
# 1 - numpy kütüphanesini import edin

# 2 - 5 elemanlı bir numpy array oluşturun

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.


In [1]:
import numpy as np

sayilar = np.array([12, 5, 7, 1, 9])

siralanmis_sayilar = np.sort(sayilar)

print("Sıralanmış array:", siralanmis_sayilar)

Sıralanmış array: [ 1  5  7  9 12]


# Problem 2

In [ ]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.


# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
 
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.


# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.


# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.


# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.


# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.


# 8- [-1 ile 1] arasında 10 adet sayı üretin.


# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.


# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?


# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?


# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?


# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.


# 14- Üretilen dizinin elemanlarını tersten yazdırın.


# 15- Üretilen matrisin ilk satırını seçiniz.


# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?


# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.


# 18- Üretilen matrisin her bir elemanının karesini alınız.


# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.


In [2]:
import numpy as np

dizi1 = np.array([10, 15, 30, 45, 60])
print("Dizi 1:", dizi1)

dizi2 = np.arange(5, 16)
print("Dizi 2:", dizi2)

dizi3 = np.arange(50, 101, 5)
print("Dizi 3:", dizi3)

dizi4 = np.zeros(10)
print("Dizi 4:", dizi4)

dizi5 = np.ones(10)
print("Dizi 5:", dizi5)

dizi6 = np.linspace(0, 100, 5)
print("Dizi 6:", dizi6)

dizi7 = np.random.randint(10, 31, 5)
print("Dizi 7:", dizi7)

dizi8 = np.random.uniform(-1, 1, 10)
print("Dizi 8:", dizi8)

matris = np.random.randint(10, 51, (3, 5))
print("Matris:\n", matris)

satir_toplamlari = np.sum(matris, axis=1)
sutun_toplamlari = np.sum(matris, axis=0)
print("Satır toplamları:", satir_toplamlari)
print("Sütun toplamları:", sutun_toplamlari)

en_buyuk = np.max(matris)
en_kucuk = np.min(matris)
ortalama = np.mean(matris)
print("En büyük:", en_buyuk, "En küçük:", en_kucuk, "Ortalama:", ortalama)

en_buyuk_indis = np.argmax(matris)
print("En büyük değerin indeksi:", en_buyuk_indis)

dizi13 = np.arange(10, 21)
print("Dizinin ilk 3 elemanı:", dizi13[:3])

ters_dizi13 = dizi13[::-1]
print("Dizinin tersten hali:", ters_dizi13)

ilk_satir = matris[0, :]
print("Matrisin ilk satırı:", ilk_satir)

elem_2_3 = matris[1, 2]
print("2. satır 3. sütundaki eleman:", elem_2_3)

ilk_elemanlar = matris[:, 0]
print("Tüm satırların ilk elemanları:", ilk_elemanlar)

matris_kare = np.square(matris)
print("Matrisin kareleri:\n", matris_kare)

yeni_matris = np.random.randint(-50, 51, (3, 5))
pozitif_ciftler = yeni_matris[(yeni_matris > 0) & (yeni_matris % 2 == 0)]
print("Pozitif çift sayılar:", pozitif_ciftler)


Dizi 1: [10 15 30 45 60]
Dizi 2: [ 5  6  7  8  9 10 11 12 13 14 15]
Dizi 3: [ 50  55  60  65  70  75  80  85  90  95 100]
Dizi 4: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Dizi 5: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Dizi 6: [  0.  25.  50.  75. 100.]
Dizi 7: [11 10 12 15 10]
Dizi 8: [-0.73833354  0.30841879  0.28026143  0.93861355  0.21119603 -0.79480464
  0.65140968 -0.65719793  0.12879313 -0.47055984]
Matris:
 [[29 22 37 17 12]
 [46 13 28 43 16]
 [45 17 16 28 17]]
Satır toplamları: [117 146 123]
Sütun toplamları: [120  52  81  88  45]
En büyük: 46 En küçük: 12 Ortalama: 25.733333333333334
En büyük değerin indeksi: 5
Dizinin ilk 3 elemanı: [10 11 12]
Dizinin tersten hali: [20 19 18 17 16 15 14 13 12 11 10]
Matrisin ilk satırı: [29 22 37 17 12]
2. satır 3. sütundaki eleman: 28
Tüm satırların ilk elemanları: [29 46 45]
Matrisin kareleri:
 [[ 841  484 1369  289  144]
 [2116  169  784 1849  256]
 [2025  289  256  784  289]]
Pozitif çift sayılar: [ 6 24  6 18 14]
